#include "formats.h"
#include "metrics.h"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <map>
#include <set>
#include <stdexcept>
#include <string>
#include <vector>

namespace {
std::string arg(int n,char**v,const std::string&k){for(int i=1;i+1<n;i++)if(v[i]==k)return v[i+1];throw std::runtime_error("missing "+k);}
struct Bucket{std::string name;uint64_t n=0,flips=0;};
struct Agg{
 uint64_t n=0,flips=0,h1n=0,h1f=0,h2n=0,h2f=0,h4n=0,h4f=0;double sum_kl=0,sum_dnll=0,sx=0,sy=0,sxx=0,syy=0,sxy=0,sum_abs=0,sum_sq=0;
 std::vector<double>kls,flipped;Bucket buckets[6]={{"<0.1"},{"0.1-0.5"},{"0.5-1"},{"1-2"},{"2-4"},{">=4"}};
 void add(const rq::RowMetrics&z){n++;sum_kl+=z.kl;sum_dnll+=z.delta_nll;kls.push_back(z.kl);flips+=z.decision_flip;if(z.decision_flip)flipped.push_back(z.ref_margin);int b=z.ref_margin<.1?0:z.ref_margin<.5?1:z.ref_margin<1?2:z.ref_margin<2?3:z.ref_margin<4?4:5;buckets[b].n++;buckets[b].flips+=z.decision_flip;if(z.ref_margin>=1){h1n++;h1f+=z.decision_flip;}if(z.ref_margin>=2){h2n++;h2f+=z.decision_flip;}if(z.ref_margin>=4){h4n++;h4f+=z.decision_flip;}double x=z.p_ref_target,y=z.p_quant_target;sx+=x;sy+=y;sxx+=x*x;syy+=y*y;sxy+=x*y;sum_abs+=std::abs(z.delta_p_target);sum_sq+=z.delta_p_target*z.delta_p_target;}
};
double pct(std::vector<double>v,double p){std::sort(v.begin(),v.end());return rq::percentile_sorted(v.data(),v.size(),p);}
double rate(uint64_t a,uint64_t b){return b?double(a)/b:0;}
void contract(const rq::RqlHeader&a,const rq::RqlHeader&b){rq::require_compatible(a,b);auto bad=[](const char*x){throw std::runtime_error(std::string("execution contract mismatch: ")+x);};if(!a.has_execution_contract||!b.has_execution_contract)bad("RQL v2");if(a.llama_commit!=b.llama_commit)bad("llama_cpp_commit");if(a.n_ctx!=b.n_ctx)bad("n_ctx");if(a.n_batch!=b.n_batch)bad("n_batch");if(a.n_ubatch!=b.n_ubatch)bad("n_ubatch");if(a.kv_k_type!=b.kv_k_type)bad("kv_k_type");if(a.kv_v_type!=b.kv_v_type)bad("kv_v_type");if(a.gpu_layers!=b.gpu_layers)bad("gpu_layers");if(a.flash_attention!=b.flash_attention)bad("flash_attention");if(a.tokenizer_add_special!=b.tokenizer_add_special)bad("tokenizer_add_special");if(a.tokenizer_parse_special!=b.tokenizer_parse_special)bad("tokenizer_parse_special");if(a.sampling!=b.sampling)bad("sampling");}
void emit(std::ostream&o,Agg&a){double n=a.n,den=std::sqrt((n*a.sxx-a.sx*a.sx)*(n*a.syy-a.sy*a.sy));o<<std::setprecision(17)<<"\"scored_positions\":"<<a.n<<",\"mean_KL\":"<<a.sum_kl/n<<",\"median_KL\":"<<pct(a.kls,.5)<<",\"P90_KL\":"<<pct(a.kls,.9)<<",\"P99_KL\":"<<pct(a.kls,.99)<<",\"mean_delta_NLL\":"<<a.sum_dnll/n<<",\"PPL_ratio\":"<<std::exp(a.sum_dnll/n)<<",\"same_top1_rate\":"<<(n-a.flips)/n<<",\"changed_top1_count\":"<<a.flips<<",\"target_probability_Pearson_r\":"<<(den?(n*a.sxy-a.sx*a.sy)/den:0)<<",\"RMS_target_probability_difference\":"<<std::sqrt(a.sum_sq/n)<<",\"MAE_target_probability_difference\":"<<a.sum_abs/n<<",\"HCDFR_at_1\":"<<rate(a.h1f,a.h1n)<<",\"HCDFR_at_2\":"<<rate(a.h2f,a.h2n)<<",\"HCDFR_at_4\":"<<rate(a.h4f,a.h4n);}
}
int main(int argc,char**argv){try{
 auto refp=arg(argc,argv,"--reference"),qp=arg(argc,argv,"--quant"),cp=arg(argc,argv,"--corpus"),prefix=arg(argc,argv,"--output"),quant_type=arg(argc,argv,"--quant-type");std::string quant_key=quant_type=="Q8_0"?"q8":quant_type=="Q6_K"?"q6":quant_type=="Q5_K_M"?"q5":quant_type=="Q4_K_M"?"q4":quant_type=="Q3_K_M"?"q3":quant_type=="Q2_K"?"q2":"quant";rq::RqlReader ref(refp),quant(qp);contract(ref.header(),quant.header());auto corpus=rq::read_segmented_corpus(cp);if(ref.header().token_sha256!=rq::sha256_file(cp))throw std::runtime_error("official corpus SHA mismatch");if(corpus.segments.size()!=128||corpus.tokens_per_segment!=768||corpus.burn_in_tokens!=256||corpus.scored_tokens_per_segment!=512||ref.header().positions!=65536)throw std::runtime_error("official geometry mismatch");
 std::ofstream flips(prefix+".flips.jsonl"),curve(prefix+".reference-confidence-flip-curve.csv"),sample(prefix+".validation-primary.jsonl");if(!flips||!curve||!sample)throw std::runtime_error("cannot create analysis output");flips<<std::setprecision(17);sample<<std::setprecision(17);
 std::vector<double>edges;for(int i=0;i<=10;i++)edges.push_back(i*.1);for(double x:{1.25,1.5,2.,2.5,3.,4.,5.,6.,8.,10.,15.,20.,std::numeric_limits<double>::infinity()})edges.push_back(x);std::vector<uint64_t>fn(edges.size()-1),ff(edges.size()-1);
 std::map<std::string,Agg>domains;std::map<uint32_t,Agg>segments;std::map<uint32_t,std::string>segment_domains;Agg overall;std::vector<float>r,q;std::set<uint64_t>selected;for(uint64_t k=0;k<128;k++)selected.insert(k*(ref.header().positions-1)/127);
 uint64_t global=0;for(auto&s:corpus.segments)for(uint32_t target=corpus.burn_in_tokens;target<corpus.tokens_per_segment;target++,global++){
  if(!ref.read(r)||!quant.read(q))throw std::runtime_error("RQL ended early");auto z=rq::calculate_metrics(r.data(),q.data(),r.size(),s.tokens[target]);overall.add(z);domains[s.domain].add(z);segments[s.segment_id].add(z);segment_domains[s.segment_id]=s.domain;auto it=std::upper_bound(edges.begin(),edges.end(),z.ref_margin);size_t bi=std::max<size_t>(1,it-edges.begin())-1;bi=std::min(bi,fn.size()-1);fn[bi]++;ff[bi]+=z.decision_flip;
  if(z.decision_flip)flips<<"{\"global_scored_position_index\":"<<global<<",\"segment_id\":"<<s.segment_id<<",\"domain\":\""<<s.domain<<"\",\"target_position_within_segment\":"<<target<<",\"target_token_id\":"<<s.tokens[target]<<",\"bf16_top1_token_id\":"<<z.ref_top1<<",\""<<quant_key<<"_top1_token_id\":"<<z.quant_top1<<",\"bf16_top2_token_id\":"<<z.ref_top2<<",\"bf16_top1_logit\":"<<z.ref_top1_logit<<",\"bf16_top2_logit\":"<<z.ref_top2_logit<<",\"bf16_margin\":"<<z.ref_margin<<",\""<<quant_key<<"_top1_logit\":"<<z.quant_top1_logit<<",\"bf16_target_probability\":"<<z.p_ref_target<<",\""<<quant_key<<"_target_probability\":"<<z.p_quant_target<<",\"KL_BF16_"<<quant_key<<"\":"<<z.kl<<"}\n";
  if(selected.count(global))sample<<"{\"position\":"<<global<<",\"target_token_id\":"<<s.tokens[target]<<",\"bf16_top1_token_id\":"<<z.ref_top1<<",\"bf16_top2_token_id\":"<<z.ref_top2<<",\""<<quant_key<<"_top1_token_id\":"<<z.quant_top1<<",\"same_top1\":"<<(z.decision_flip?"false":"true")<<",\"bf16_margin\":"<<z.ref_margin<<",\"KL_BF16_"<<quant_key<<"\":"<<z.kl<<",\"bf16_target_probability\":"<<z.p_ref_target<<",\""<<quant_key<<"_target_probability\":"<<z.p_quant_target<<"}\n";
 }
 ref.require_finished();quant.require_finished();
 curve<<"margin_lower_inclusive,margin_upper_exclusive,number_of_positions,decision_flips,flip_rate\n"<<std::setprecision(17);for(size_t i=0;i<fn.size();i++)curve<<edges[i]<<','<<(std::isinf(edges[i+1])?"inf":std::to_string(edges[i+1]))<<','<<fn[i]<<','<<ff[i]<<','<<rate(ff[i],fn[i])<<'\n';
 std::ofstream ds(prefix+".domain-metrics.csv");ds<<"domain,scored_positions,mean_KL,median_KL,mean_delta_NLL,same_top1_rate,changed_top1_count,HCDFR_at_1,HCDFR_at_2,HCDFR_at_4,target_probability_Pearson_r,RMS_target_probability_difference\n"<<std::setprecision(17);const char*order[]={"english_prose","chinese_prose","mixed_en_zh","code","structured_data","math_symbolic","technical_it","dialogue_instruction"};for(auto d:order){auto&a=domains.at(d);double n=a.n,den=std::sqrt((n*a.sxx-a.sx*a.sx)*(n*a.syy-a.sy*a.sy));ds<<d<<','<<a.n<<','<<a.sum_kl/n<<','<<pct(a.kls,.5)<<','<<a.sum_dnll/n<<','<<(n-a.flips)/n<<','<<a.flips<<','<<rate(a.h1f,a.h1n)<<','<<rate(a.h2f,a.h2n)<<','<<rate(a.h4f,a.h4n)<<','<<(den?(n*a.sxy-a.sx*a.sy)/den:0)<<','<<std::sqrt(a.sum_sq/n)<<'\n';}
 std::ofstream ss(prefix+".segment-sufficient-statistics.csv");ss<<"segment_id,domain,scored_positions,sum_KL,sum_delta_NLL,top1_flips,margin_ge_1_positions,margin_ge_1_flips,margin_ge_2_positions,margin_ge_2_flips,margin_ge_4_positions,margin_ge_4_flips,sum_squared_target_probability_difference,sum_absolute_target_probability_difference\n"<<std::setprecision(17);for(auto&kv:segments){auto id=kv.first;auto&a=kv.second;ss<<id<<','<<segment_domains.at(id)<<','<<a.n<<','<<a.sum_kl<<','<<a.sum_dnll<<','<<a.flips<<','<<a.h1n<<','<<a.h1f<<','<<a.h2n<<','<<a.h2f<<','<<a.h4n<<','<<a.h4f<<','<<a.sum_sq<<','<<a.sum_abs<<'\n';}
 std::ofstream summary(prefix+".primary-summary.json");summary<<"{\n  \"quant_type\":\""<<quant_type<<"\",\n  \"overall\":{";emit(summary,overall);summary<<"},\n  \"margin_buckets\":[\n";for(int i=0;i<6;i++){auto&b=overall.buckets[i];summary<<"    {\"bucket\":\""<<b.name<<"\",\"number_of_positions\":"<<b.n<<",\"decision_flips\":"<<b.flips<<",\"flip_rate\":"<<rate(b.flips,b.n)<<"}"<<(i<5?",":"")<<"\n";}std::sort(overall.flipped.begin(),overall.flipped.end());summary<<"  ],\n  \"flipped_margin_distribution\":";if(overall.flipped.empty())summary<<"null";else summary<<"{\"minimum\":"<<overall.flipped.front()<<",\"median\":"<<pct(overall.flipped,.5)<<",\"P90\":"<<pct(overall.flipped,.9)<<",\"P95\":"<<pct(overall.flipped,.95)<<",\"P99\":"<<pct(overall.flipped,.99)<<",\"maximum\":"<<overall.flipped.back()<<"}";summary<<"\n}\n";
 std::cout<<"analyzed_positions="<<global<<" changed_top1_count="<<overall.flips<<" mean_KL="<<std::setprecision(12)<<overall.sum_kl/overall.n<<"\n";return 0;
}catch(const std::exception&e){std::cerr<<"error: "<<e.what()<<"\n";return 1;}}
