#include "formats.h"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <iomanip>
#include <limits>
#include <sstream>
#include <stdexcept>

namespace rq {
namespace {
constexpr char TMAGIC[8] = {'R','Q','T','O','K','E','N','\0'};
constexpr char RMAGIC[8] = {'R','Q','L','O','G','I','T','\0'};
constexpr char SMAGIC[8] = {'R','Q','S','E','G','\0','\0','\0'};
static_assert(RQL_V1_HEADER_SIZE == 8+4+4+4+4+8+32+128+41);
static_assert(RQL_V2_HEADER_SIZE == 8+4+4+4+4+8+32+32+41+128+4*14);
void exact(std::istream &s, char *p, size_t n) { s.read(p,n); if (size_t(s.gcount()) != n) throw std::runtime_error("truncated binary file"); }
void u32o(std::ostream&s,uint32_t v){char b[4];for(int i=0;i<4;i++)b[i]=char(v>>(8*i));s.write(b,4);}
void u64o(std::ostream&s,uint64_t v){char b[8];for(int i=0;i<8;i++)b[i]=char(v>>(8*i));s.write(b,8);}
uint32_t u32i(std::istream&s){unsigned char b[4];exact(s,(char*)b,4);return uint32_t(b[0])|uint32_t(b[1])<<8|uint32_t(b[2])<<16|uint32_t(b[3])<<24;}
uint64_t u64i(std::istream&s){unsigned char b[8];exact(s,(char*)b,8);uint64_t v=0;for(int i=7;i>=0;i--)v=(v<<8)|b[i];return v;}
void fixed(std::ostream&s,const std::string&v,size_t n){if(v.size()>=n)throw std::runtime_error("header string too long");std::vector<char>b(n);memcpy(b.data(),v.data(),v.size());s.write(b.data(),b.size());}
std::string fixedin(std::istream&s,size_t n){std::vector<char>b(n);exact(s,b.data(),n);auto z=std::find(b.begin(),b.end(),'\0');return std::string(b.begin(),z);}
void validate_v2(const RqlHeader&h){if(!h.vocab_size)throw std::runtime_error("zero vocabulary");if(!h.positions)throw std::runtime_error("zero positions");if(h.logits_dtype!=DTYPE_F32)throw std::runtime_error("RQL is not float32");if(!h.has_execution_contract)throw std::runtime_error("RQL v2 execution contract is missing");if(std::all_of(h.model_sha256.begin(),h.model_sha256.end(),[](uint8_t x){return x==0;}))throw std::runtime_error("RQL v2 model SHA256 is missing");if(std::all_of(h.token_sha256.begin(),h.token_sha256.end(),[](uint8_t x){return x==0;}))throw std::runtime_error("RQL v2 token SHA256 is missing");if(h.model_id.empty())throw std::runtime_error("RQL v2 model identity is missing");if(!h.n_ctx||!h.n_batch||!h.n_ubatch)throw std::runtime_error("RQL v2 execution geometry is missing");if(h.n_batch>h.n_ctx||h.n_ubatch>h.n_batch)throw std::runtime_error("invalid RQL v2 execution geometry");if(h.kv_k_type!=KV_F16||h.kv_v_type!=KV_F16)throw std::runtime_error("unsupported RQL v2 KV type");if(h.flash_attention>FLASH_ENABLED)throw std::runtime_error("invalid RQL v2 Flash Attention state");if(h.sampling!=SAMPLING_NONE)throw std::runtime_error("unsupported RQL v2 sampling mode");if(h.llama_commit.empty())throw std::runtime_error("RQL v2 llama.cpp commit is missing");}
void header(std::ostream&s,const RqlHeader&h){
 s.write(RMAGIC,8);u32o(s,h.schema_version);
 if(h.schema_version==RQL_V1_VERSION){if(h.header_size!=RQL_V1_HEADER_SIZE)throw std::runtime_error("bad RQL v1 header size");u32o(s,RQL_V1_HEADER_SIZE);u32o(s,h.vocab_size);u32o(s,DTYPE_F32);u64o(s,h.positions);s.write((char*)h.token_sha256.data(),32);fixed(s,h.model_id,128);fixed(s,h.llama_commit,41);return;}
 if(h.schema_version!=RQL_V2_VERSION||h.header_size!=RQL_V2_HEADER_SIZE)throw std::runtime_error("unsupported RQL writer schema/header size");validate_v2(h);u32o(s,RQL_V2_HEADER_SIZE);u32o(s,h.vocab_size);u32o(s,h.logits_dtype);u64o(s,h.positions);s.write((char*)h.model_sha256.data(),32);s.write((char*)h.token_sha256.data(),32);fixed(s,h.llama_commit,41);fixed(s,h.model_id,128);u32o(s,h.n_ctx);u32o(s,h.n_batch);u32o(s,h.n_ubatch);u32o(s,h.kv_k_type);u32o(s,h.kv_v_type);u32o(s,uint32_t(h.gpu_layers));u32o(s,h.flash_attention);u32o(s,h.tokenizer_add_special);u32o(s,h.tokenizer_parse_special);u32o(s,h.sampling);for(int i=0;i<4;i++)u32o(s,0);
}
RqlHeader read_header(std::istream&s){char m[8];exact(s,m,8);if(memcmp(m,RMAGIC,8))throw std::runtime_error("bad RQL magic");RqlHeader h;h.schema_version=u32i(s);h.header_size=u32i(s);if(h.schema_version==RQL_V1_VERSION){if(h.header_size!=RQL_V1_HEADER_SIZE)throw std::runtime_error("bad RQL v1 header size");h.vocab_size=u32i(s);h.logits_dtype=u32i(s);if(!h.vocab_size)throw std::runtime_error("zero vocabulary");if(h.logits_dtype!=DTYPE_F32)throw std::runtime_error("RQL is not float32");h.positions=u64i(s);exact(s,(char*)h.token_sha256.data(),32);h.model_id=fixedin(s,128);h.llama_commit=fixedin(s,41);return h;}if(h.schema_version!=RQL_V2_VERSION)throw std::runtime_error("unsupported RQL version");if(h.header_size!=RQL_V2_HEADER_SIZE)throw std::runtime_error("bad RQL v2 header size");h.vocab_size=u32i(s);h.logits_dtype=u32i(s);h.positions=u64i(s);exact(s,(char*)h.model_sha256.data(),32);exact(s,(char*)h.token_sha256.data(),32);h.llama_commit=fixedin(s,41);h.model_id=fixedin(s,128);h.n_ctx=u32i(s);h.n_batch=u32i(s);h.n_ubatch=u32i(s);h.kv_k_type=u32i(s);h.kv_v_type=u32i(s);h.gpu_layers=int32_t(u32i(s));h.flash_attention=u32i(s);auto add=u32i(s),parse=u32i(s);if(add>1||parse>1)throw std::runtime_error("invalid RQL v2 tokenizer boolean");h.tokenizer_add_special=add!=0;h.tokenizer_parse_special=parse!=0;h.sampling=u32i(s);for(int i=0;i<4;i++)if(u32i(s)!=0)throw std::runtime_error("nonzero RQL v2 reserved field");h.has_execution_contract=true;validate_v2(h);return h;}

// Small, dependency-free SHA-256 implementation for stable corpus identity.
uint32_t rotr(uint32_t x,int n){return(x>>n)|(x<<(32-n));}
struct Sha { uint32_t h[8]={0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19}; uint64_t n=0; std::vector<uint8_t>b;
void block(const uint8_t*p){static const uint32_t k[64]={0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2};uint32_t w[64];for(int i=0;i<16;i++)w[i]=uint32_t(p[4*i])<<24|uint32_t(p[4*i+1])<<16|uint32_t(p[4*i+2])<<8|p[4*i+3];for(int i=16;i<64;i++){auto a=rotr(w[i-15],7)^rotr(w[i-15],18)^(w[i-15]>>3),z=rotr(w[i-2],17)^rotr(w[i-2],19)^(w[i-2]>>10);w[i]=w[i-16]+a+w[i-7]+z;}uint32_t a=h[0],c=h[2],d=h[3],e=h[4],f=h[5],g=h[6],q=h[7],bb=h[1];for(int i=0;i<64;i++){uint32_t s1=rotr(e,6)^rotr(e,11)^rotr(e,25),ch=(e&f)^(~e&g),t1=q+s1+ch+k[i]+w[i],s0=rotr(a,2)^rotr(a,13)^rotr(a,22),maj=(a&bb)^(a&c)^(bb&c),t2=s0+maj;q=g;g=f;f=e;e=d+t1;d=c;c=bb;bb=a;a=t1+t2;}h[0]+=a;h[1]+=bb;h[2]+=c;h[3]+=d;h[4]+=e;h[5]+=f;h[6]+=g;h[7]+=q;}
void add(const uint8_t*p,size_t z){n+=z;while(z--){b.push_back(*p++);if(b.size()==64){block(b.data());b.clear();}}}std::array<uint8_t,32> done(){uint64_t bits=n*8;b.push_back(0x80);while(b.size()%64!=56)b.push_back(0);for(int i=7;i>=0;i--)b.push_back(uint8_t(bits>>(8*i)));for(size_t i=0;i<b.size();i+=64)block(b.data()+i);std::array<uint8_t,32>o{};for(int i=0;i<8;i++)for(int j=0;j<4;j++)o[4*i+j]=uint8_t(h[i]>>(24-8*j));return o;}};
}

void write_tokens(const std::string&p,const std::vector<int32_t>&v){std::ofstream o(p,std::ios::binary);if(!o)throw std::runtime_error("cannot create token file");o.write(TMAGIC,8);u32o(o,TOKEN_VERSION);u32o(o,0);u64o(o,v.size());for(auto x:v)u32o(o,uint32_t(x));if(!o)throw std::runtime_error("token write failed");}
std::vector<int32_t> read_tokens(const std::string&p){std::ifstream s(p,std::ios::binary);if(!s)throw std::runtime_error("cannot open token file");char m[8];exact(s,m,8);if(memcmp(m,TMAGIC,8))throw std::runtime_error("bad token magic");if(u32i(s)!=TOKEN_VERSION)throw std::runtime_error("unsupported token version");if(u32i(s)!=0)throw std::runtime_error("bad token flags");auto n=u64i(s);if(n>(1ull<<31))throw std::runtime_error("unreasonable token count");std::vector<int32_t>v(n);for(auto&x:v)x=int32_t(u32i(s));char x;if(s.read(&x,1))throw std::runtime_error("trailing token data");return v;}
SegmentedCorpus read_segmented_corpus(const std::string&p){std::ifstream s(p,std::ios::binary);if(!s)throw std::runtime_error("cannot open RQSEG");char m[8];exact(s,m,8);if(memcmp(m,SMAGIC,8))throw std::runtime_error("bad RQSEG magic");if(u32i(s)!=RQSEG_VERSION)throw std::runtime_error("unsupported RQSEG version");if(u32i(s)!=RQSEG_HEADER_SIZE)throw std::runtime_error("bad RQSEG header size");SegmentedCorpus c;auto count=u32i(s);c.tokens_per_segment=u32i(s);c.burn_in_tokens=u32i(s);c.scored_tokens_per_segment=u32i(s);auto flags=u32i(s);if(flags&~3u)throw std::runtime_error("bad RQSEG tokenizer flags");c.tokenizer_add_special=flags&1;c.tokenizer_parse_special=flags&2;exact(s,(char*)c.model_sha256.data(),32);exact(s,(char*)c.token_payload_sha256.data(),32);c.llama_commit=fixedin(s,41);c.model_id=fixedin(s,115);if(!count||!c.tokens_per_segment||c.burn_in_tokens+c.scored_tokens_per_segment!=c.tokens_per_segment)throw std::runtime_error("invalid RQSEG dimensions");c.segments.reserve(count);for(uint32_t i=0;i<count;i++){Segment z;z.segment_id=u32i(s);z.domain=fixedin(s,32);exact(s,(char*)z.token_sha256.data(),32);if(z.domain.empty()||(i&&z.segment_id<=c.segments.back().segment_id))throw std::runtime_error("invalid RQSEG segment metadata");z.tokens.resize(c.tokens_per_segment);for(auto&t:z.tokens)t=int32_t(u32i(s));c.segments.push_back(std::move(z));}char x;if(s.read(&x,1))throw std::runtime_error("trailing RQSEG data");return c;}
std::array<uint8_t,32> sha256_file(const std::string&p){std::ifstream s(p,std::ios::binary);if(!s)throw std::runtime_error("cannot hash file");Sha h;char b[65536];while(s){s.read(b,sizeof b);h.add((uint8_t*)b,s.gcount());}return h.done();}
std::string hex(const std::array<uint8_t,32>&a){std::ostringstream s;s<<std::hex<<std::setfill('0');for(auto x:a)s<<std::setw(2)<<unsigned(x);return s.str();}
std::pair<int32_t,int32_t> top2(const float*p,uint32_t n){if(n<2)throw std::runtime_error("vocabulary has fewer than two tokens");int32_t a=0,b=1;if(p[b]>p[a])std::swap(a,b);for(uint32_t i=2;i<n;i++)if(p[i]>p[a]){b=a;a=i;}else if(p[i]>p[b])b=i;return{a,b};}
RqlWriter::RqlWriter(const std::string&p,const RqlHeader&h):out_(p,std::ios::binary),h_(h){if(!out_)throw std::runtime_error("cannot create RQL");header(out_,h_);}
void RqlWriter::write(const float*p){if(written_>=h_.positions)throw std::runtime_error("too many RQL rows");static_assert(sizeof(float)==4);out_.write((char*)p,size_t(h_.vocab_size)*4);if(!out_)throw std::runtime_error("RQL write failed");written_++;}
void RqlWriter::close(){if(out_.is_open()){if(written_!=h_.positions)throw std::runtime_error("wrong RQL row count");out_.close();}}
RqlWriter::~RqlWriter(){if(out_.is_open())out_.close();}
RqlReader::RqlReader(const std::string&p):in_(p,std::ios::binary){if(!in_)throw std::runtime_error("cannot open RQL");h_=read_header(in_);}
bool RqlReader::read(std::vector<float>&v){if(read_==h_.positions)return false;v.resize(h_.vocab_size);exact(in_,(char*)v.data(),v.size()*4);read_++;return true;}
void RqlReader::require_finished(){if(read_!=h_.positions)throw std::runtime_error("RQL rows not consumed");char x;if(in_.read(&x,1))throw std::runtime_error("trailing RQL data");}
void require_compatible(const RqlHeader&a,const RqlHeader&b,CompatibilityMode mode){auto fail=[](const char*f){throw std::runtime_error(std::string("incompatible RQL field: ")+f);};if(a.vocab_size!=b.vocab_size)fail("vocab_size");if(a.token_sha256!=b.token_sha256)fail("frozen_token_file_sha256");if(a.positions!=b.positions)fail("number_of_positions");if(mode==CompatibilityMode::Basic)return;if(!a.has_execution_contract||!b.has_execution_contract)fail("schema_version (strict mode requires RQL v2)");if(a.model_sha256!=b.model_sha256)fail("model_sha256");if(a.llama_commit!=b.llama_commit)fail("llama_cpp_commit");if(a.n_ctx!=b.n_ctx)fail("n_ctx");if(a.n_batch!=b.n_batch)fail("n_batch");if(a.n_ubatch!=b.n_ubatch)fail("n_ubatch");if(a.kv_k_type!=b.kv_k_type)fail("kv_k_type");if(a.kv_v_type!=b.kv_v_type)fail("kv_v_type");if(a.gpu_layers!=b.gpu_layers)fail("gpu_layers");if(a.flash_attention!=b.flash_attention)fail("flash_attention_resolved");if(a.tokenizer_add_special!=b.tokenizer_add_special)fail("tokenizer_add_special");if(a.tokenizer_parse_special!=b.tokenizer_parse_special)fail("tokenizer_parse_special");if(a.sampling!=b.sampling)fail("sampling");}
Comparison compare(const std::string&a,const std::string&b,std::ostream*out,CompatibilityMode mode){RqlReader x(a),y(b);require_compatible(x.header(),y.header(),mode);Comparison c;std::vector<float>u,v;for(uint64_t i=0;x.read(u)&&y.read(v);i++){auto tu=top2(u.data(),u.size()),tv=top2(v.data(),v.size());bool s1=tu.first==tv.first,s2=tu.second==tv.second;c.changed_top1+=!s1;c.changed_top2+=!s2;double row_sum=0,row_sq=0;float row_max=0;for(size_t j=0;j<u.size();j++){uint32_t ub=0,vb=0;memcpy(&ub,&u[j],4);memcpy(&vb,&v[j],4);if(ub!=vb){if(!c.differing_values){c.first_differing_position=i;c.first_differing_vocab_id=j;}c.differing_values++;}float d=std::abs(u[j]-v[j]);row_max=std::max(row_max,d);row_sum+=d;row_sq+=double(d)*d;}c.max_abs=std::max(c.max_abs,row_max);c.sum_abs+=row_sum;c.sum_sq+=row_sq;c.values+=u.size();c.positions++;if(out)*out<<"{\"position\":"<<i<<",\"top1_same\":"<<(s1?"true":"false")<<",\"top2_same\":"<<(s2?"true":"false")<<",\"max_abs_logit_delta\":"<<row_max<<",\"mean_abs_logit_delta\":"<<row_sum/u.size()<<",\"RMS_logit_delta\":"<<sqrt(row_sq/u.size())<<"}\n";}x.require_finished();y.require_finished();return c;}
}
