#include "formats.h"
#include "llama.h"
#include <algorithm>
#include <chrono>
#include <cstdlib>
#include <ctime>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

static std::string arg(int n,char**v,const std::string&k,bool optional=false){for(int i=1;i+1<n;i++)if(v[i]==k)return v[i+1];if(optional)return{};throw std::runtime_error("missing "+k);}
static int iarg(int n,char**v,const std::string&k){return std::stoi(arg(n,v,k));}
static int iarg_default(int n,char**v,const std::string&k,int fallback){auto s=arg(n,v,k,true);return s.empty()?fallback:std::stoi(s);}
static bool barg(int n,char**v,const std::string&k){auto s=arg(n,v,k);if(s=="true")return true;if(s=="false")return false;throw std::runtime_error(k+" must be true or false");}
static std::string json(const std::string&s){std::string o="\"";for(unsigned char c:s){if(c=='\"'||c=='\\')o+='\\',o+=c;else if(c=='\n')o+="\\n";else if(c<32){const char*x="0123456789abcdef";o+="\\u00";o+=x[c>>4];o+=x[c&15];}else o+=c;}return o+'\"';}
static void nullable(std::ostream&o,const char*name){const char*v=std::getenv(name);if(v&&*v)o<<json(v);else o<<"null";}
static std::string timestamp(){auto now=std::chrono::system_clock::now();auto t=std::chrono::system_clock::to_time_t(now);std::tm tm{};
#ifdef _WIN32
gmtime_s(&tm,&t);
#else
gmtime_r(&t,&tm);
#endif
char b[32];std::strftime(b,sizeof b,"%Y-%m-%dT%H:%M:%SZ",&tm);return b;}
int main(int argc,char**argv){try{
    auto model_path=arg(argc,argv,"--model"),token_path=arg(argc,argv,"--tokens",true),segmented_path=arg(argc,argv,"--segmented-corpus",true),prefix=arg(argc,argv,"--output"),quantized_arg=arg(argc,argv,"--quantized-model",true),rqseg_model_sha=arg(argc,argv,"--rqseg-model-sha256",true);if(token_path.empty()==segmented_path.empty())throw std::runtime_error("supply exactly one of --tokens or --segmented-corpus");bool quantized_model=!quantized_arg.empty()&&quantized_arg=="true";if(!quantized_arg.empty()&&quantized_arg!="true"&&quantized_arg!="false")throw std::runtime_error("--quantized-model must be true or false");int nctx=iarg(argc,argv,"--context-size"),ngpu=iarg(argc,argv,"--gpu-layers"),batch_size=iarg_default(argc,argv,"--batch-size",512),rql_version=iarg_default(argc,argv,"--rql-version",2),score_limit=iarg_default(argc,argv,"--score-limit-per-segment",0);bool add_special=false,parse_special=false;std::string flash;if(rql_version==2){add_special=barg(argc,argv,"--tokenizer-add-special");parse_special=barg(argc,argv,"--tokenizer-parse-special");flash=arg(argc,argv,"--flash-attention");if(flash!="enabled"&&flash!="disabled")throw std::runtime_error("--flash-attention must be enabled or disabled for RQL v2");}else if(rql_version!=1)throw std::runtime_error("--rql-version must be 1 or 2");if(!segmented_path.empty()&&rql_version!=2)throw std::runtime_error("segmented corpora require RQL v2");if(batch_size<=0||batch_size>nctx)throw std::runtime_error("batch-size must be in 1..context-size");if(score_limit<0)throw std::runtime_error("score-limit-per-segment must be nonnegative");
    std::vector<int32_t> tokens;rq::SegmentedCorpus corpus;if(token_path.empty())corpus=rq::read_segmented_corpus(segmented_path);else tokens=rq::read_tokens(token_path);if(!tokens.empty()&&(tokens.size()<2||tokens.size()>size_t(nctx)))throw std::runtime_error("single segment must contain 2..context-size tokens");if(!segmented_path.empty()){if(corpus.tokens_per_segment>uint32_t(nctx))throw std::runtime_error("RQSEG segment exceeds context-size");if(corpus.tokenizer_add_special!=add_special||corpus.tokenizer_parse_special!=parse_special)throw std::runtime_error("RQSEG tokenizer behavior does not match execution contract");if(score_limit>int(corpus.scored_tokens_per_segment))throw std::runtime_error("score-limit-per-segment exceeds RQSEG scored geometry");if(!rqseg_model_sha.empty()&&rqseg_model_sha!=rq::hex(corpus.model_sha256))throw std::runtime_error("RQSEG model/tokenizer SHA256 does not match explicit --rqseg-model-sha256");}
    llama_backend_init();auto mp=llama_model_default_params();mp.n_gpu_layers=ngpu;std::unique_ptr<llama_model,decltype(&llama_model_free)>m(llama_model_load_from_file(model_path.c_str(),mp),llama_model_free);if(!m)throw std::runtime_error("model load failed");if(quantized_model&&llama_model_ftype(m.get())==LLAMA_FTYPE_MOSTLY_BF16)throw std::runtime_error("--quantized-model cannot be used with a BF16 model");
    auto cp=llama_context_default_params();cp.n_ctx=nctx;cp.n_batch=batch_size;cp.n_ubatch=batch_size;cp.type_k=GGML_TYPE_F16;cp.type_v=GGML_TYPE_F16;if(rql_version==2)cp.flash_attn_type=flash=="enabled"?LLAMA_FLASH_ATTN_TYPE_ENABLED:LLAMA_FLASH_ATTN_TYPE_DISABLED;
    const llama_vocab*vocab=llama_model_get_vocab(m.get());uint32_t nv=llama_vocab_n_tokens(vocab);auto check=[&](const std::vector<int32_t>&v){for(auto t:v)if(t<0||uint32_t(t)>=nv)throw std::runtime_error("token ID outside model vocabulary");};if(segmented_path.empty())check(tokens);else for(auto&s:corpus.segments)check(s.tokens);char desc[128]={};llama_model_desc(m.get(),desc,sizeof desc);
    uint32_t scored_per_segment=segmented_path.empty()?0:(score_limit?uint32_t(score_limit):corpus.scored_tokens_per_segment);rq::RqlHeader h;h.schema_version=rql_version;h.header_size=rql_version==1?rq::RQL_V1_HEADER_SIZE:rq::RQL_V2_HEADER_SIZE;h.vocab_size=nv;h.positions=segmented_path.empty()?tokens.size()-1:uint64_t(corpus.segments.size())*scored_per_segment;auto corpus_path=segmented_path.empty()?token_path:segmented_path;h.token_sha256=rq::sha256_file(corpus_path);h.model_id=desc;h.llama_commit="70adb1b4cea5ee39f867792c78dc59320921eda7";if(rql_version==2){h.model_sha256=rq::sha256_file(model_path);if(!segmented_path.empty()&&rqseg_model_sha.empty()&&h.model_sha256!=corpus.model_sha256&&!quantized_model)throw std::runtime_error("RQSEG model SHA256 does not match inference model; for a tokenizer-fixture-bound RQSEG supply its explicit --rqseg-model-sha256");h.n_ctx=nctx;h.n_batch=batch_size;h.n_ubatch=batch_size;h.kv_k_type=rq::KV_F16;h.kv_v_type=rq::KV_F16;h.gpu_layers=ngpu;h.flash_attention=flash=="enabled"?rq::FLASH_ENABLED:rq::FLASH_DISABLED;h.tokenizer_add_special=add_special;h.tokenizer_parse_special=parse_special;h.sampling=rq::SAMPLING_NONE;h.has_execution_contract=true;}rq::RqlWriter writer(prefix+".rql",h);std::ofstream pos(prefix+".positions.jsonl");if(!pos)throw std::runtime_error("cannot create positions metadata");pos<<std::setprecision(9);
    uint64_t global=0;auto infer=[&](uint32_t sid,const std::string&domain,const std::vector<int32_t>&ids,uint32_t first_input,uint32_t wanted){std::unique_ptr<llama_context,decltype(&llama_free)>ctx(llama_init_from_model(m.get(),cp),llama_free);if(!ctx)throw std::runtime_error("context creation failed");llama_batch batch=llama_batch_init(cp.n_batch,0,1);uint64_t at=0,decode_tokens=std::min<uint64_t>(ids.size(),uint64_t(first_input)+wanted+1);while(at<decode_tokens){uint32_t count=std::min<uint64_t>(cp.n_batch,decode_tokens-at);batch.n_tokens=count;uint32_t outputs=0;for(uint32_t j=0;j<count;j++){uint64_t p=at+j;batch.token[j]=ids[p];batch.pos[j]=p;batch.n_seq_id[j]=1;batch.seq_id[j][0]=0;batch.logits[j]=(p>=first_input&&p<uint64_t(first_input)+wanted&&p+1<ids.size());outputs+=batch.logits[j]!=0;}int rc=llama_decode(ctx.get(),batch);if(rc)throw std::runtime_error("llama_decode failed with code "+std::to_string(rc));const float*all=llama_get_logits(ctx.get());if(outputs&&!all)throw std::runtime_error("llama_get_logits returned null");uint32_t row=0;for(uint32_t j=0;j<count;j++){uint64_t p=at+j;if(!batch.logits[j])continue;const float*l=all+size_t(row++)*nv;auto top=rq::top2(l,nv);writer.write(l);pos<<"{\"global_scored_row_index\":"<<global++<<",\"segment_id\":"<<sid<<",\"domain\":"<<json(domain)<<",\"input_position\":"<<p<<",\"target_position\":"<<p+1<<",\"local_input_position\":"<<p<<",\"target_local_position\":"<<p+1<<",\"input_token_id\":"<<ids[p]<<",\"target_token_id\":"<<ids[p+1]<<",\"top1_token_id\":"<<top.first<<",\"top2_token_id\":"<<top.second<<",\"top1_logit\":"<<l[top.first]<<",\"top2_logit\":"<<l[top.second]<<",\"reference_margin\":"<<l[top.first]-l[top.second]<<"}\n";}at+=count;}llama_batch_free(batch);};if(segmented_path.empty())infer(0,"legacy_single_segment",tokens,0,tokens.size()-1);else for(auto&s:corpus.segments)infer(s.segment_id,s.domain,s.tokens,corpus.burn_in_tokens-1,scored_per_segment);if(global!=h.positions)throw std::runtime_error("scored row count does not match RQL header");
    writer.close();
    if(rql_version==2){
        std::ofstream e(prefix+".execution.json");if(!e)throw std::runtime_error("cannot create execution sidecar");
        std::string command;for(int i=0;i<argc;i++){if(i)command+=' ';command+=argv[i];}
        e<<"{\n  \"schema_version\": 1,\n  \"timestamp_utc\": "<<json(timestamp())<<",\n  \"executable\": "<<json(argv[0])<<",\n  \"build_identity\": "<<json(std::string("C++17 ")+__DATE__+" "+__TIME__)<<",\n  \"inference_model_role\": "<<json(quantized_model?"quantized":"reference")<<",\n  \"physical_gpu_name\": ";nullable(e,"RAMGPT_GPU_NAME");e<<",\n  \"gpu_uuid\": ";nullable(e,"RAMGPT_GPU_UUID");e<<",\n  \"gpu_pci_identity\": ";nullable(e,"RAMGPT_GPU_PCI_ID");e<<",\n  \"cuda_driver_version\": ";nullable(e,"RAMGPT_CUDA_DRIVER_VERSION");e<<",\n  \"cuda_runtime_build_version\": ";nullable(e,"RAMGPT_CUDA_RUNTIME_VERSION");e<<",\n  \"cuda_visible_devices\": ";nullable(e,"CUDA_VISIBLE_DEVICES");e<<",\n  \"visible_cuda_device_mapping\": {\"logical_device\": 0, \"environment\": ";nullable(e,"CUDA_VISIBLE_DEVICES");e<<"},\n  \"llama_cpp_commit\": "<<json(h.llama_commit)<<",\n  \"model_path\": "<<json(model_path)<<",\n  \"model_sha256\": "<<json(rq::hex(h.model_sha256))<<",\n  \"token_path\": "<<json(corpus_path)<<",\n  \"token_sha256\": "<<json(rq::hex(h.token_sha256))<<",\n  \"rqseg_model_or_tokenizer_sha256\": "<<(segmented_path.empty()?"null":json(rq::hex(corpus.model_sha256)))<<",\n  \"rqseg_binding_mode\": "<<json(rqseg_model_sha.empty()?"inference_model_sha_default":"explicit_tokenizer_fixture_sha")<<",\n  \"n_ctx\": "<<nctx<<",\n  \"n_batch\": "<<batch_size<<",\n  \"n_ubatch\": "<<batch_size<<",\n  \"kv_k_type\": \"F16\",\n  \"kv_v_type\": \"F16\",\n  \"gpu_layers\": "<<ngpu<<",\n  \"flash_attention\": {\"requested\": "<<json(flash)<<", \"resolved\": "<<json(flash)<<", \"resolution_method\": \"explicit llama context parameter; context creation succeeded\"},\n  \"tokenizer_add_special\": "<<(add_special?"true":"false")<<",\n  \"tokenizer_parse_special\": "<<(parse_special?"true":"false")<<",\n  \"sampling\": \"none\",\n  \"score_limit_per_segment\": "<<score_limit<<",\n  \"command_line\": "<<json(command)<<"\n}\n";
    }
    std::cout<<"rql_schema_version="<<h.schema_version<<" scored_positions="<<h.positions<<" vocab_size="<<nv<<" token_sha256="<<rq::hex(h.token_sha256)<<"\n";m.reset();llama_backend_free();return 0;
}catch(const std::exception&e){std::cerr<<"error: "<<e.what()<<"\n";return 1;}}
