#include "formats.h"
#include "metrics.h"
#include "llama.h"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <memory>
#include <regex>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace {
std::string arg(int n,char**v,const std::string&k,bool optional=false){for(int i=1;i+1<n;i++)if(v[i]==k)return v[i+1];if(optional)return{};throw std::runtime_error("missing "+k);}
int iarg(int n,char**v,const std::string&k){return std::stoi(arg(n,v,k));}
int iarg_default(int n,char**v,const std::string&k,int fallback){auto s=arg(n,v,k,true);return s.empty()?fallback:std::stoi(s);}
int64_t field(const std::string&s,const std::string&k){std::regex r("\\\""+k+"\\\"\\s*:\\s*(-?[0-9]+)");std::smatch m;if(!std::regex_search(s,m,r))throw std::runtime_error("positions JSONL missing "+k);return std::stoll(m[1]);}
llama_ftype expected_ftype(const std::string&s){if(s=="Q8_0")return LLAMA_FTYPE_MOSTLY_Q8_0;if(s=="Q6_K")return LLAMA_FTYPE_MOSTLY_Q6_K;if(s=="Q5_K_M")return LLAMA_FTYPE_MOSTLY_Q5_K_M;if(s=="Q4_K_M")return LLAMA_FTYPE_MOSTLY_Q4_K_M;if(s=="Q3_K_M")return LLAMA_FTYPE_MOSTLY_Q3_K_M;if(s=="Q2_K")return LLAMA_FTYPE_MOSTLY_Q2_K;if(s=="IQ1_M")return LLAMA_FTYPE_MOSTLY_IQ1_M;throw std::runtime_error("unsupported Phase 0C quant type: "+s);}
std::vector<int32_t> read_targets(const std::string&p,const std::vector<int32_t>&expected){std::ifstream f(p);if(!f)throw std::runtime_error("cannot open reference positions");std::vector<int32_t>v;std::string line;while(std::getline(f,line)){if(line.empty())continue;auto id=field(line,"target_token_id");if(v.size()>=expected.size()||expected[v.size()]!=id)throw std::runtime_error("reference positions do not match frozen corpus");v.push_back(id);}return v;}
std::set<uint64_t> selected(uint64_t n){if(n<100)throw std::runtime_error("validation dump requires at least 100 positions");std::set<uint64_t>s;for(uint64_t k=0;k<100;k++)s.insert(k*(n-1)/99);return s;}
std::set<uint64_t> selected_file(const std::string&p,uint64_t n){std::ifstream f(p);if(!f)throw std::runtime_error("cannot open validation positions file");std::set<uint64_t>s;std::string line;uint64_t lineno=0;while(std::getline(f,line)){lineno++;auto first=line.find_first_not_of(" \t\r");if(first==std::string::npos)continue;auto last=line.find_last_not_of(" \t\r");auto value=line.substr(first,last-first+1);size_t used=0;long long x;try{x=std::stoll(value,&used);}catch(...){throw std::runtime_error("invalid validation position at line "+std::to_string(lineno));}if(used!=value.size()||x<0||uint64_t(x)>=n)throw std::runtime_error("validation position out of range at line "+std::to_string(lineno));if(!s.insert(uint64_t(x)).second)throw std::runtime_error("duplicate validation position "+std::to_string(x));}if(s.empty())throw std::runtime_error("validation positions file is empty");return s;}
void u32(std::ostream&o,uint32_t x){char b[4];for(int i=0;i<4;i++)b[i]=char(x>>(8*i));o.write(b,4);}void u64(std::ostream&o,uint64_t x){char b[8];for(int i=0;i<8;i++)b[i]=char(x>>(8*i));o.write(b,8);}
double pct(std::vector<double>v,double p){std::sort(v.begin(),v.end());return rq::percentile_sorted(v.data(),v.size(),p);}
struct Bucket {const char*name;uint64_t n=0,flips=0;};
}

int main(int argc,char**argv){try{
 auto model_path=arg(argc,argv,"--model"),quant_type=arg(argc,argv,"--quant-type"),token_path=arg(argc,argv,"--tokens",true),segmented_path=arg(argc,argv,"--segmented-corpus",true),ref_path=arg(argc,argv,"--reference"),positions_path=arg(argc,argv,"--reference-positions"),prefix=arg(argc,argv,"--output"),dump_path=arg(argc,argv,"--validation-dump",true),validation_positions=arg(argc,argv,"--validation-positions",true);if(token_path.empty()==segmented_path.empty())throw std::runtime_error("supply exactly one of --tokens or --segmented-corpus");int nctx=iarg(argc,argv,"--context-size"),ngpu=iarg(argc,argv,"--gpu-layers"),batch_size=iarg_default(argc,argv,"--batch-size",512);if(batch_size<=0||batch_size>nctx)throw std::runtime_error("batch-size must be in 1..context-size");if(!validation_positions.empty()&&dump_path.empty())throw std::runtime_error("--validation-positions requires --validation-dump");
 std::vector<std::vector<int32_t>> runs;std::vector<uint32_t> first_inputs;std::vector<int32_t> expected_targets;rq::SegmentedCorpus corpus;auto corpus_path=token_path.empty()?segmented_path:token_path;if(segmented_path.empty()){auto t=rq::read_tokens(token_path);if(t.size()<2||t.size()>size_t(nctx))throw std::runtime_error("single segment must contain 2..context-size tokens");for(size_t i=1;i<t.size();i++)expected_targets.push_back(t[i]);runs.push_back(std::move(t));first_inputs.push_back(0);}else{corpus=rq::read_segmented_corpus(segmented_path);if(corpus.tokens_per_segment>uint32_t(nctx))throw std::runtime_error("RQSEG segment exceeds context-size");for(auto&s:corpus.segments){runs.push_back(s.tokens);first_inputs.push_back(corpus.burn_in_tokens-1);for(uint32_t p=corpus.burn_in_tokens;p<corpus.tokens_per_segment;p++)expected_targets.push_back(s.tokens[p]);}}rq::RqlReader ref(ref_path);auto rh=ref.header();if(rh.llama_commit!="70adb1b4cea5ee39f867792c78dc59320921eda7")throw std::runtime_error("unsupported reference llama.cpp commit");if(rh.token_sha256!=rq::sha256_file(corpus_path))throw std::runtime_error("frozen corpus SHA256 does not match reference");if(rh.positions!=expected_targets.size())throw std::runtime_error("reference scored-position count mismatch");if(rh.has_execution_contract){if(rh.n_ctx!=uint32_t(nctx))throw std::runtime_error("incompatible RQL field: n_ctx");if(rh.n_batch!=uint32_t(batch_size))throw std::runtime_error("incompatible RQL field: n_batch");if(rh.n_ubatch!=uint32_t(batch_size))throw std::runtime_error("incompatible RQL field: n_ubatch");if(rh.kv_k_type!=rq::KV_F16||rh.kv_v_type!=rq::KV_F16)throw std::runtime_error("incompatible RQL field: KV type");if(rh.gpu_layers!=ngpu)throw std::runtime_error("incompatible RQL field: gpu_layers");if(rh.sampling!=rq::SAMPLING_NONE)throw std::runtime_error("incompatible RQL field: sampling");}auto targets=read_targets(positions_path,expected_targets);if(targets.size()!=rh.positions)throw std::runtime_error("reference positions row count mismatch");
 llama_backend_init();auto mp=llama_model_default_params();mp.n_gpu_layers=ngpu;std::unique_ptr<llama_model,decltype(&llama_model_free)>model(llama_model_load_from_file(model_path.c_str(),mp),llama_model_free);if(!model)throw std::runtime_error("quant model load failed");if(llama_model_ftype(model.get())!=expected_ftype(quant_type))throw std::runtime_error("model file type does not match --quant-type "+quant_type);const llama_vocab*vocab=llama_model_get_vocab(model.get());uint32_t nv=llama_vocab_n_tokens(vocab);if(nv!=rh.vocab_size)throw std::runtime_error("quant vocabulary size does not match reference");for(auto&ids:runs)for(auto t:ids)if(t<0||uint32_t(t)>=nv)throw std::runtime_error("token ID outside quant vocabulary");
 auto cp=llama_context_default_params();cp.n_ctx=nctx;cp.n_batch=batch_size;cp.n_ubatch=batch_size;cp.type_k=GGML_TYPE_F16;cp.type_v=GGML_TYPE_F16;if(rh.has_execution_contract)cp.flash_attn_type=rh.flash_attention==rq::FLASH_ENABLED?LLAMA_FLASH_ATTN_TYPE_ENABLED:LLAMA_FLASH_ATTN_TYPE_DISABLED;
 std::ofstream rows(prefix+".positions.jsonl");if(!rows)throw std::runtime_error("cannot create output JSONL");rows<<std::setprecision(17);std::ofstream dump;std::set<uint64_t>selection;if(!dump_path.empty()){selection=validation_positions.empty()?selected(rh.positions):selected_file(validation_positions,rh.positions);dump.open(dump_path,std::ios::binary);if(!dump)throw std::runtime_error("cannot create validation dump");dump.write("RQSELQ4\0",8);u32(dump,1);u32(dump,nv);u32(dump,selection.size());u32(dump,0);}
 std::vector<double>kls,dnll,flipped_margins;kls.reserve(rh.positions);dnll.reserve(rh.positions);Bucket buckets[]={{"<0.1"},{"0.1-0.5"},{"0.5-1"},{"1-2"},{"2-4"},{">=4"}};uint64_t flips=0,h1n=0,h1f=0,h2n=0,h2f=0,h4n=0,h4f=0;double sx=0,sy=0,sxx=0,syy=0,sxy=0,sum_abs_dp=0,sum_sq_dp=0;
 std::vector<float>rrow;uint64_t position=0;for(size_t run_i=0;run_i<runs.size();run_i++){auto&ids=runs[run_i];std::unique_ptr<llama_context,decltype(&llama_free)>ctx(llama_init_from_model(model.get(),cp),llama_free);if(!ctx)throw std::runtime_error("context creation failed");llama_batch batch=llama_batch_init(cp.n_batch,0,1);uint64_t at=0;while(at<ids.size()){uint32_t count=std::min<uint64_t>(cp.n_batch,ids.size()-at);batch.n_tokens=count;uint32_t outputs=0;for(uint32_t j=0;j<count;j++){uint64_t p=at+j;batch.token[j]=ids[p];batch.pos[j]=p;batch.n_seq_id[j]=1;batch.seq_id[j][0]=0;batch.logits[j]=p>=first_inputs[run_i]&&p+1<ids.size();outputs+=batch.logits[j]!=0;}int rc=llama_decode(ctx.get(),batch);if(rc)throw std::runtime_error("llama_decode failed with code "+std::to_string(rc));const float*qall=llama_get_logits(ctx.get());if(outputs&&!qall)throw std::runtime_error("llama_get_logits returned null");uint32_t outrow=0;for(uint32_t j=0;j<count;j++){if(!batch.logits[j])continue;if(!ref.read(rrow))throw std::runtime_error("reference ended early");const float*q=qall+size_t(outrow++)*nv;auto z=rq::calculate_metrics(rrow.data(),q,nv,targets[position]);kls.push_back(z.kl);dnll.push_back(z.delta_nll);flips+=z.decision_flip;if(z.decision_flip)flipped_margins.push_back(z.ref_margin);int bi=z.ref_margin<.1?0:z.ref_margin<.5?1:z.ref_margin<1?2:z.ref_margin<2?3:z.ref_margin<4?4:5;buckets[bi].n++;buckets[bi].flips+=z.decision_flip;if(z.ref_margin>=1){h1n++;h1f+=z.decision_flip;}if(z.ref_margin>=2){h2n++;h2f+=z.decision_flip;}if(z.ref_margin>=4){h4n++;h4f+=z.decision_flip;}double x=z.p_ref_target,y=z.p_quant_target;sx+=x;sy+=y;sxx+=x*x;syy+=y*y;sxy+=x*y;sum_abs_dp+=std::abs(z.delta_p_target);sum_sq_dp+=z.delta_p_target*z.delta_p_target;
 rows<<"{\"position\":"<<position<<",\"target_token_id\":"<<targets[position]<<",\"ref_top1_id\":"<<z.ref_top1<<",\"ref_top2_id\":"<<z.ref_top2<<",\"quant_top1_id\":"<<z.quant_top1<<",\"quant_top2_id\":"<<z.quant_top2<<",\"ref_top1_logit\":"<<z.ref_top1_logit<<",\"ref_top2_logit\":"<<z.ref_top2_logit<<",\"quant_top1_logit\":"<<z.quant_top1_logit<<",\"quant_top2_logit\":"<<z.quant_top2_logit<<",\"ref_margin\":"<<z.ref_margin<<",\"decision_flip\":"<<(z.decision_flip?"true":"false")<<",\"kl_ref_quant\":"<<z.kl<<",\"p_ref_target\":"<<z.p_ref_target<<",\"p_quant_target\":"<<z.p_quant_target<<",\"delta_p_target\":"<<z.delta_p_target<<",\"nll_ref\":"<<z.nll_ref<<",\"nll_quant\":"<<z.nll_quant<<",\"delta_nll\":"<<z.delta_nll<<"}\n";
 if(selection.count(position)){u64(dump,position);dump.write((char*)q,size_t(nv)*4);}position++;}at+=count;}llama_batch_free(batch);}
 ref.require_finished();if(position!=rh.positions)throw std::runtime_error("inference position count mismatch");double n=position,mean_kl=0,mean_dnll=0;for(double x:kls)mean_kl+=x;for(double x:dnll)mean_dnll+=x;mean_kl/=n;mean_dnll/=n;double denom=std::sqrt((n*sxx-sx*sx)*(n*syy-sy*sy)),pearson=denom?((n*sxy-sx*sy)/denom):0;std::sort(flipped_margins.begin(),flipped_margins.end());auto fp=[&](double p){return rq::percentile_sorted(flipped_margins.data(),flipped_margins.size(),p);};
 std::ofstream summary(prefix+".summary.json");if(!summary)throw std::runtime_error("cannot create summary");summary<<std::setprecision(17)<<"{\n  \"methodology\": \"METHODOLOGY VALIDATION ONLY\",\n  \"quant_type\": \""<<quant_type<<"\",\n  \"quantization\": \""<<quant_type<<" without importance matrix\",\n  \"number_of_positions\": "<<position<<",\n  \"mean_KL\": "<<mean_kl<<",\n  \"median_KL\": "<<pct(kls,.5)<<",\n  \"P90_KL\": "<<pct(kls,.9)<<",\n  \"P99_KL\": "<<pct(kls,.99)<<",\n  \"mean_delta_NLL\": "<<mean_dnll<<",\n  \"PPL_ratio\": "<<std::exp(mean_dnll)<<",\n  \"same_top1_rate\": "<<(n-flips)/n<<",\n  \"changed_top1_count\": "<<flips<<",\n  \"correct_token_probability_Pearson_r\": "<<pearson<<",\n  \"RMS_target_probability_change\": "<<std::sqrt(sum_sq_dp/n)<<",\n  \"mean_absolute_target_probability_change\": "<<sum_abs_dp/n<<",\n  \"margin_buckets\": [\n";for(int i=0;i<6;i++)summary<<"    {\"bucket\": \""<<buckets[i].name<<"\", \"number_of_positions\": "<<buckets[i].n<<", \"decision_flips\": "<<buckets[i].flips<<", \"flip_rate\": "<<(buckets[i].n?double(buckets[i].flips)/buckets[i].n:0)<<"}"<<(i<5?",":"")<<"\n";summary<<"  ],\n  \"HCDFR_at_1\": "<<(h1n?double(h1f)/h1n:0)<<",\n  \"HCDFR_at_2\": "<<(h2n?double(h2f)/h2n:0)<<",\n  \"HCDFR_at_4\": "<<(h4n?double(h4f)/h4n:0)<<",\n  \"flipped_margin_count\": "<<flipped_margins.size();if(flipped_margins.empty())summary<<",\n  \"flipped_margin_statistics\": null\n}\n";else summary<<",\n  \"flipped_margin_statistics\": {\"median\": "<<fp(.5)<<", \"P90\": "<<fp(.9)<<", \"P95\": "<<fp(.95)<<", \"P99\": "<<fp(.99)<<", \"maximum\": "<<flipped_margins.back()<<"}\n}\n";
 std::cout<<std::setprecision(12)<<"METHODOLOGY VALIDATION ONLY\nnumber_of_positions="<<position<<"\nmean_KL="<<mean_kl<<"\nmedian_KL="<<pct(kls,.5)<<"\nP90_KL="<<pct(kls,.9)<<"\nP99_KL="<<pct(kls,.99)<<"\nmean_delta_NLL="<<mean_dnll<<"\nPPL_ratio="<<std::exp(mean_dnll)<<"\nsame_top1_rate="<<(n-flips)/n<<"\nchanged_top1_count="<<flips<<"\ncorrect_token_probability_Pearson_r="<<pearson<<"\nRMS_target_probability_change="<<std::sqrt(sum_sq_dp/n)<<"\nmean_absolute_target_probability_change="<<sum_abs_dp/n<<"\n";for(auto&b:buckets)std::cout<<"margin_bucket["<<b.name<<"]="<<b.n<<","<<b.flips<<","<<(b.n?double(b.flips)/b.n:0)<<"\n";std::cout<<"HCDFR@1="<<(h1n?double(h1f)/h1n:0)<<"\nHCDFR@2="<<(h2n?double(h2f)/h2n:0)<<"\nHCDFR@4="<<(h4n?double(h4f)/h4n:0)<<"\n";
 model.reset();llama_backend_free();return 0;
}catch(const std::exception&e){std::cerr<<"error: "<<e.what()<<"\n";return 1;}}
